In [2]:
# --- Read & Inspect ---
import pandas as pd

df = pd.read_excel(r"C:\Users\PANRIT\ALL\Pranit Main\Study\python\Pandas_Polars_Numpy\pca_student_data.xlsx")
print(df.shape)
print(df.info())
print(df.describe())
print(df.head())

(2000, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2000 non-null   object
 1   Marks   2000 non-null   float64
 2   Hours   2000 non-null   float64
 3   Age     2000 non-null   int64
 4   Sleep   2000 non-null   float64
dtypes: float64(3), int64(1), object(1)
memory usage: 78.3+ KB
None
             Marks        Hours          Age        Sleep
count  2000.000000  2000.000000  2000.000000  2000.000000
mean     68.404950     5.855200    20.101000     6.988700
std       9.161322     1.051226     1.954152     1.197668
min      38.100000     2.500000    16.000000     3.400000
25%      62.000000     5.200000    19.000000     6.100000
50%      68.200000     5.900000    20.000000     7.000000
75%      74.500000     6.600000    21.000000     7.800000
max      97.300000     9.500000    28.000000    10.000000
           Name  Marks  Hours  Age  Sleep
0  Student_0001   55.7    5.3   21    6.2
1  Student_0002   63.2    5.9   20    6.8
2  Student_0003   59.9    6.2   21    6.0
3  Student_0004   64.7    6.5   23    6.6
4  Student_0005   59.9    5.2   20    4.7

In [ ]:
# --- Selection & Extraction ---
import pandas as pd

df = pd.read_excel(r"C:\Users\PANRIT\ALL\Pranit Main\Study\python\Pandas_Polars_Numpy\pca_student_data.xlsx", index_col="Name")

print(df.loc["Student_0001" , "Marks"]) # --> Extract specific value
print(df.iloc[1,2])

print(df.loc["Student_0002"])           # --> Extract entire row value
print(df.iloc[2])

print(df.loc[:,"Age"])                  # --> Extract specific column
print(df.iloc[:,2])

print(df.loc["Student_0002":"Student_0007", "Marks": "Age"]) # --> Extract specific group
print(df.iloc[1:10,1:3])

              Marks  Hours  Age
Name
Student_0002   63.2    5.9   20
Student_0003   59.9    6.2   21
Student_0004   64.7    6.5   23
Student_0005   59.9    5.2   20
Student_0006   77.7    6.4   20
Student_0007   55.7    3.2   23
              Hours  Age
Name
Student_0002    5.9   20
Student_0003    6.2   21
Student_0004    6.5   23
Student_0005    5.2   20
Student_0006    6.4   20
Student_0007    3.2   23
Student_0008    5.6   22
Student_0009    5.2   19
Student_0010    6.2   21

In [ ]:
# --- Filter & Condition ---
import pandas as pd
df = pd.read_excel(r"C:\Users\PANRIT\ALL\Pranit Main\Study\python\Pandas_Polars_Numpy\pca_student_data.xlsx")

df = df[df["Name"] == "Student_0001"]
print(df)
df = df[df["Age"] > 25]
print(df)
df = df[df["Marks"].isin([50,60])]
print(df)
df = df[df["Name"].str.contains("0005")]

           Name  Marks  Hours  Age  Sleep
4  Student_0005   59.9    5.2   20    4.7

In [ ]:
# --- GroupBy & Aggrigaitons ---
import pandas as pd
df = pd.read_excel(r"C:\Users\PANRIT\ALL\Pranit Main\Study\python\Pandas_Polars_Numpy\pca_student_data.xlsx")

df = df.groupby(by="Age").sum()
df

,Name,Marks,Hours,Sleep
Age,,,,
16,Student_0014Student_0038Student_0050Student_00...,4603.7,389.0,460.6
17,Student_0015Student_0020Student_0024Student_00...,8324.2,696.6,855.6
18,Student_0017Student_0019Student_0027Student_00...,15996.0,1363.8,1641.6
19,Student_0009Student_0011Student_0012Student_00...,23151.1,1996.0,2345.6
20,Student_0002Student_0005Student_0006Student_00...,28622.9,2438.4,2912.1
21,Student_0001Student_0003Student_0010Student_00...,24872.0,2126.4,2532.3
22,Student_0008Student_0035Student_0048Student_00...,16326.8,1389.2,1697.7
23,Student_0004Student_0007Student_0021Student_00...,8954.8,787.3,912.8
24,Student_0032Student_0107Student_0126Student_01...,4254.8,370.2,443.9
25,Student_0114Student_0180Student_0221Student_05...,1451.8,134.0,148.2
26,Student_0479Student_1616Student_1958,194.7,14.7,20.0
28,Student_0210,57.1,4.8,7.0

In [39]:
# --- Merge / Join ---
import pandas as pd
df = pd.read_excel(r"C:\Users\PANRIT\ALL\Pranit Main\Study\python\Pandas_Polars_Numpy\pca_student_data.xlsx")
df2 = pd.DataFrame({"Name": "None"})

df = df.merge(df2, how="inner", left_on="column", right_on="column")

ValueError: If using all scalar values, you must pass an index

In [46]:
# --- Sorting & Ranking ---
import pandas as pd
df = pd.read_excel(r"C:\Users\PANRIT\ALL\Pranit Main\Study\python\Pandas_Polars_Numpy\pca_student_data.xlsx")

df1 = df.nlargest(columns="Marks", n=4)
df2 = df.nsmallest(columns="Age", n=5)
df3 = df.sort_values(by="Name",ascending=False)
df4 = df.sort_values(by=["Name", "Marks"])
df4

              Name  Marks  Hours  Age  Sleep
0     Student_0001   55.7    5.3   21    6.2
1     Student_0002   63.2    5.9   20    6.8
2     Student_0003   59.9    6.2   21    6.0
3     Student_0004   64.7    6.5   23    6.6
4     Student_0005   59.9    5.2   20    4.7
...            ...    ...    ...  ...    ...
1995  Student_1996   86.4    6.1   22    7.0
1996  Student_1997   72.9    7.8   20    4.5
1997  Student_1998   57.9    4.8   18    6.6
1998  Student_1999   85.5    5.8   20    9.0
1999  Student_2000   81.8    4.6   19    7.4

[2000 rows x 5 columns]